#system global variables
hds.explorer.mail.configured: true
hds.explorer.constraints.father.age.min: 12
hds.explorer.constraints.mother.age.min: 12
hds.explorer.constraints.head.age.min: 12
hds.explorer.constraints.spouse.age.min: 16
hds.explorer.constraints.respondent.age.min: 12
hds.explorer.constraints.gender.checking: true
hds.explorer.system.language: "en"
hds.explorer.system.codegenerator: "org.philimone.hds.explorer.server.settings.generator.DefaultCodeGenerator"
hds.explorer.system.codegenerator_rules.incremental: "FILL_GAPS"
hds.explorer.system.region.head.support: false
hds.explorer.system.path: "/var/lib/hds-explorer"


# Default datasource for HDS-Database
# MySQL Config
  #dataSource.pooled: true
  #dataSource.driverClassName: com.mysql.cj.jdbc.Driver
  #dataSource.dialect: org.hibernate.dialect.MySQL8Dialect
  #dataSource.username: hds_explorer
  #dataSource.password: d33_2019xx
  #dataSource.url: jdbc:mysql://localhost/hds_explorer_db?createDatabaseIfNotExist=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false

# Postgres Config
  #dataSource.pooled: true
  #dataSource.jmxExport: true
  #dataSource.driverClassName: org.postgresql.Driver
  #dataSource.dialect: org.hibernate.dialect.PostgreSQL94Dialect
  #dataSource.username: hds_explorer
  #dataSource.password: d33_2019xx
  #dataSource.url: "jdbc:postgresql://localhost:5432/hds_explorer_db"

# Don't forget to turn on access from a less secure app in your Gmail account configuration, otherwise, google will block it and return this error.
#
grails:
  mail:
    host: "smtp.gmail.com"
    port: 465
    username: "youremailaccount@gmail.com"
    password: "youremailaccountpassword"
    props:
      mail.smtp.auth: "true"
      mail.smtp.socketFactory.port: "465"
      mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
      mail.smtp.socketFactory.fallback: "false"